name: CI/CD Docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/letters-api
  VERSION: ${{ github.sha }}
  NAME: letters-api

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy
    runs-on: [ self-hosted, label-go ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # env 설정
      - name: Env
        run: |
          touch .env
          echo "${{ secrets.ENV_CONTENT }}" >> .env

      - name: Docker DB up
        run: docker-compose up -d
      
      - name: Run server
        uses: cypress-io/github-action@v2
        with:
          start: npm run start
          wait-on: 'http://localhost:3000'
          record: true
