name: CI/CD Docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

env:
  NAME: letters-api

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      # env 설정
      - name: Env
        run: |
          touch .env
          echo "${{ secrets.ENV_CONTENT }}" >> .env

      - name: Docker DB up
        run: docker-compose up -d
      
      - name: Install module
        run: npm install

      - name: Run server
        run: (npm run start &)
